[package]
edition = '2021'
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Patrick Mukherjee <patrick@mukherjee.de>"]

[dependencies]
aoc-main = { version = "*", features = ["bench"] }# for day 4
regex = "1"
